package pantallacatalogoscuentas;

import bd.Comparador;
import bd.Conexion;
import bd.CuentaBd;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.List;
import javax.swing.tree.DefaultMutableTreeNode;
import modelo.Cuenta;

public class MenuCatalogoCuentas extends javax.swing.JDialog {

    NuevaCuenta n;
    CatalogoCuentas cc;

    public MenuCatalogoCuentas(java.awt.Frame parent, boolean modal) {

        super(parent, modal);
        initComponents();
        btnCancelar.setVisible(false);
        btnCancelar.setEnabled(false);
        Conexion.conectar();
        crearArbol();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCatalogoCuentas = new javax.swing.JButton();
        btnAgregarCuenta = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCatalogoCuentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgIconos/btnMCC2.png"))); // NOI18N
        btnCatalogoCuentas.setText("Catálogo De Cuentas");
        btnCatalogoCuentas.setBorder(null);
        btnCatalogoCuentas.setBorderPainted(false);
        btnCatalogoCuentas.setContentAreaFilled(false);
        btnCatalogoCuentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCatalogoCuentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCatalogoCuentas.setIconTextGap(-4);
        btnCatalogoCuentas.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgIconos/btnMCC1.png"))); // NOI18N
        btnCatalogoCuentas.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgIconos/btnMCC3.png"))); // NOI18N
        btnCatalogoCuentas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCatalogoCuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatalogoCuentasActionPerformed(evt);
            }
        });
        getContentPane().add(btnCatalogoCuentas, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, -1, 120));

        btnAgregarCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgIconos/btnAC2.png"))); // NOI18N
        btnAgregarCuenta.setText("Agregar Cuenta");
        btnAgregarCuenta.setBorder(null);
        btnAgregarCuenta.setBorderPainted(false);
        btnAgregarCuenta.setContentAreaFilled(false);
        btnAgregarCuenta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarCuenta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregarCuenta.setIconTextGap(10);
        btnAgregarCuenta.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgIconos/btnAC1.png"))); // NOI18N
        btnAgregarCuenta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgIconos/btnAC3.png"))); // NOI18N
        btnAgregarCuenta.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAgregarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 98, -1));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 734, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktopPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 734, -1));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgIconos/btnCancelar2.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setBorder(null);
        btnCancelar.setBorderPainted(false);
        btnCancelar.setContentAreaFilled(false);
        btnCancelar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCancelar.setIconTextGap(-4);
        btnCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgIconos/btnCancelar3.png"))); // NOI18N
        btnCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgIconos/btnCancelar1.png"))); // NOI18N
        btnCancelar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, -1, 110));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCuentaActionPerformed
        btnAgregarCuenta.setEnabled(false);
        btnAgregarCuenta.setVisible(false);
        btnCancelar.setEnabled(true);
        btnCancelar.setVisible(true);
        n = new NuevaCuenta();
        jDesktopPane1.add(n);
        n.setSize(jDesktopPane1.getWidth(), jDesktopPane1.getHeight());//nC.setLocation(null);
        n.setBorder(null);
        n.show();
    }//GEN-LAST:event_btnAgregarCuentaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        n.dispose();
        btnCancelar.setVisible(false);
        btnCancelar.setEnabled(false);
        btnAgregarCuenta.setEnabled(true);
        btnAgregarCuenta.setVisible(true);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCatalogoCuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatalogoCuentasActionPerformed
        cc = new CatalogoCuentas();
        jDesktopPane1.add(cc);
        cc.setSize(jDesktopPane1.getWidth(), jDesktopPane1.getHeight());//nC.setLocation(null);
        cc.setBorder(null);
        cc.show();
    }//GEN-LAST:event_btnCatalogoCuentasActionPerformed

    public void crearArbol() {
        //cc.getTree().removeAll();
        CuentaBd cbd = new CuentaBd();
        try {
            List<Cuenta> c = cbd.obtenerCuentas();
            Collections.sort(c, new Comparador());
            DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("Catálogo De Cuentas");
            DefaultMutableTreeNode padre = new DefaultMutableTreeNode(); 
            DefaultMutableTreeNode hijo;
            
            for(Cuenta cuenta: c){
                if(cuenta.getPadre()==0){
                    String s = String.valueOf(cuenta.getCodigo())+". "+cuenta.getNombre();
                    raiz.add(new DefaultMutableTreeNode(s));
                }
                else{
                    
                }
                //System.out.println(cuenta.getCodigo()+","+cuenta.getNombre()+","+cuenta.getPadre());
            }
            
        } catch (SQLException e) {

        }
    }
    
    public void arbol(){
        List<List<DefaultMutableTreeNode>> nodos = new ArrayList<>();
        CuentaBd cbd = new CuentaBd();
        int i = String.valueOf(cbd.getMax()).toCharArray().length;
        try {
            List<Cuenta> c = cbd.obtenerCuentas();
            Collections.sort(c, new Comparador());
            //DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("Catálogo De Cuentas");
            //DefaultMutableTreeNode padre = new DefaultMutableTreeNode(); 
            //DefaultMutableTreeNode hijo;
            
            for(Cuenta cuenta: c){
                if(cuenta.getPadre()==0){
                    //String s = String.valueOf(cuenta.getCodigo())+". "+cuenta.getNombre();
                    //raiz.add(new DefaultMutableTreeNode(s));
                    
                }
                else{
                    
                }
            }
        }catch(SQLException e){
            
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCatalogoCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCatalogoCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCatalogoCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCatalogoCuentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuCatalogoCuentas dialog = new MenuCatalogoCuentas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCuenta;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCatalogoCuentas;
    private javax.swing.JDesktopPane jDesktopPane1;
    // End of variables declaration//GEN-END:variables
}
